apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: dev-envi-namespace
spec:
  replicas: 3
  selector:
   matchLabels:
     app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: tomcat-nginx
      labels:
        app: tomcat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - tomcat
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: tomcat
          image: prajwal1327/mytomcat:1.1.2
