apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecretfiles
  containers:
  - name: tomcat
    image: prajwal1327/mytomcat:1.1.6
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/user/local/tomcat/webapps"
